# Generated by Django 5.0.1 on 2024-01-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
